### ISSUE TITLE
Automated testing failure

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/coulombs-law#1]
Lint issues:
```
/data/share/phet/continuous-testing/snapshot-1489714797460/coulombs-law/js/coulombs-law/model/CoulombsLawModel.js
  19:38  error  'Property' is not defined                                                                         no-undef
  19:52  error  'Vector2' is not defined                                                                          no-undef
  21:24  error  'TVector2' is not defined                                                                         no-undef
  35:22  error  Range: using native constructor instead of project module, did you forget a requirejs statement?  no-html-constructors
  37:26  error  'Color' is not defined                                                                            no-undef
  38:26  error  'Color' is not defined                                                                            no-undef
  40:23  error  'Charge' is not defined                                                                           no-undef
  41:23  error  'Charge' is not defined                                                                           no-undef
  43:24  error  'InverseSquareLawCommonConstants' is not defined                                                  no-undef
  44:25  error  'InverseSquareLawCommonConstants' is not defined                                                  no-undef
  46:5   error  'InverseSquareLawModel' is not defined                                                            no-undef
  46:39  error  'InverseSquareLawCommonConstants' is not defined                                                  no-undef
```

**Comment by jessegreenberg** [comment]
@mbarlow12 can you take a look at this?  I think these things were included yesterday, maybe it just wasn't committed?

**Comment by mbarlow12** [comment]
I saw that this AM. Made changes and ran the linter. It completed cleanly,
so I think it should be ok now. I pushed it as well. Let me know if I
missed something with it.

-Michael

**Comment by jessegreenberg** [comment]
This issue is still present in master, could you try to push again?

**Comment by mbarlow12** [comment]
Rewrote the commit from this morning to reference the issue.  I think that should do it.

**Comment by jessegreenberg** [comment]
Looks good, thanks! But getting a new errror:

```
coulombs-law
Uncaught Error: Script error for: COULOMBS_LAW/model/Charge
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: COULOMBS_LAW/model/Charge
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://localhost:8080/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (http://localhost:8080/sherpa/lib/require-2.1.11.js:1681:26)
```

It looks like Charge.js wasn't checked in.
